### ISSUE TITLE
Updates in external functions signatures does not register properly

### ISSUE THREAD

**Issue by must** [loreanvictor/tyfon#14]
When updating the backend API's signature to make a property optional it can result in an error on the frontend where the SDK package is out of date (i.e. property not marked as optional) hence resulting in a typescript error.

Further testing is required.

**Comment by loreanvictor** [comment]
Couldn't reproduce. Steps that I followed:

1. I setup a [sample server](https://loreanvictor.github.io/tyfon/#setup-a-server) and [client](https://loreanvictor.github.io/tyfon/#setup-a-client).
2. I ran everything to ensure everything works
3. I modified server code like this:
    ```ts
    export const getMessage = async (user: User, greetings?: string) => `${greetings || 'Hellow'} ${user.name}!`;
    ```
4. I rebuilt and re-ran the server, and re-installed client SDK:
    ```bash
    # on the server side code
    tyfon b
    tyfon s
    ```
    ```bash
    # on the client side code
    tyfon i
    ```
    Signatures are updated instantly. Code works fine.
5. I changed the server code to this:
    ```ts
    export const getMessage = async (user: User, greetings: string) => `${greetings || 'Hellow'} ${user.name}!`;
    ```
6. Rebuilt and re-ran server, re-installed client SDK. Client has now errors (correctly).
7. Reverted server code to optional `greetings` argument. Rebuilt and reran, re-installed SDK. Everything fine.

@must Am I missing something?

**Comment by must** [comment]
So I figured that this works only if the client is restarted on my end. If the client is kept running (even when running `tyron i` on the side), it just results in the types not being updated.

**Comment by loreanvictor** [comment]
well unless your client run-time reloads, there is no way for newly installed type definitions to be loaded. since the client-side runtime is independent of TyFON, this is not an issue with TyFON. I recommend configuring your client-side runtime so that it reloads on changes to `node_modules/@api` (typically `node_modules` is ignored by client runtimes such as webpack dev server).

**Comment by must** [comment]
Just for future reference. You can easily exclude the folder in the web pack config file:
```Javascript
module: {
    rules: [
      {
        // ...
        exclude: /node_modules\/(?!(\@api)\/).*/,
      }
    ]
  },
```

**Comment by loreanvictor** [comment]
> Just for future reference. You can easily exclude the folder in the webpack config file:
> 
> ```Javascript
> 
> module: {
> 
>     rules: [
> 
>       {
> 
>         // ...
> 
>         exclude: /node_modules\/(?!(\@api)\/).*/,
> 
>       }
> 
>     ]
> 
>   },
> 
> ```

will add this to the docs, perfect (also would appreciate a PR adding this to the docs)
