### ISSUE TITLE
Calling a remote function with undefined

### ISSUE THREAD

**Issue by must** [loreanvictor/tyfon#15]
It appears that when calling a remote function without the parameter (e.g. `function_call()`), then it would result in an undefined value in an optional parameter (e.g. `function function_call(param?: string)`). However, when it comes explicitly from an undefined value (or through a variable) (e.g. `function_call(undefined)`), then it will be sent as the string "undefined".

**Comment by loreanvictor** [comment]
this should be fixed now. update TyFON:
```bash
npm i - g tyfon
```
and re-install client SDKs.
